/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ipc1.tarea2_202100125_s2;

/**
 *
 * @author Lenovo
 */
public class Bienvenida extends javax.swing.JFrame {

    String nombre;
    String apellido;
    String password;
   Usuario_Tarea2 usuarios[];
   
    public Bienvenida(String nombre,String apellido,String password, Usuario_Tarea2 usuarios[]) {
        this.nombre = nombre; 
        this.apellido = apellido;
        this.password= password;
        this.usuarios = usuarios;
        initComponents();
        Nombre.setText(this.nombre);
        Nombre2.setText(this.nombre);
        Apellido.setText(this.apellido);
        Secreto.setText(this.password);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Secreto = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Nombre2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FondoB = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido");
        setMaximumSize(new java.awt.Dimension(563, 475));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Secreto.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        getContentPane().add(Secreto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 210, 20));

        Apellido.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        getContentPane().add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 210, 20));

        Nombre2.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        getContentPane().add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 210, 20));

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        jLabel5.setText("Carnet:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, 20));

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        jLabel4.setText("Apellido:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, 20));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, 20));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel1.setText("Información: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        Nombre.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 120, 40));

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 48)); // NOI18N
        jLabel2.setText("¡Bienvenido!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        FondoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ultimo Intento.jpg"))); // NOI18N
        getContentPane().add(FondoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       // try {
        //           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
         //              if ("Nimbus".equals(info.getName())) {
        //                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
           //                break;
           //            }
          //         }
          //     } catch (ClassNotFoundException ex) {
           //        java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
           //    } catch (InstantiationException ex) {
           //        java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
           //    } catch (IllegalAccessException ex) {
           //        java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
           //    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //       java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            //   }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
          //      new Bienvenida().setVisible(true);
        //    }
      //  });
   // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel FondoB;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Secreto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
